app/models/project.rb, app/models/project_technology.rb, app/models/technology.rb, app/models/user.rb, app/models/user_technology.rb, test/models/project_technology_test.rb, test/models/technology_test.rb, test/models/user_technology_test.rb
added three technology models, updated associations
=> updated and added new models

app/models/project.rb, app/models/user.rb, db/migrate/20200819115550_change_column_name_for_project_technologies.rb, db/migrate/20200819115800_change_column_name_for_user_technologies.rb, db/schema.rb
Reverts kkoutoup/find_a_coding_buddy#4
=> Revert "Updating models and schema. Tested in console. Associations seems to …"

app/models/project.rb, app/models/technology.rb
=> project model and technology model changed

app/models/project.rb, app/models/user.rb, db/migrate/20200820124527_add_completed_column_to_projects.rb, db/schema.rb
added a single column completed (default:false) to projects table
=> Testing db in console updating models

app/controllers/applications_controller.rb, app/views/users/profile.html.erb, config/routes.rb
We can now accept applications 🎉 
https://recordit.co/E5KrJoBSgM
ping @kkoutoup @Vishal151 @E-F-J
=> accept feature

app/controllers/applications_controller.rb, app/controllers/projects_controller.rb, app/views/components/_form_project.html.erb, app/views/components/_homepage_banner.html.erb, app/views/pages/home.html.erb, app/views/projects/new.html.erb
hey dudes, i guess we can PR my version and then merge Alex's changes into it?
=> tidied up components html and fixed application new-create

app/assets/stylesheets/components/_navbar.scss, app/views/projects/index.html.erb, app/views/projects/show.html.erb, app/views/users/profile.html.erb, app/views/users/show.html.erb, db/seeds.rb
fiddled around a bit. @Vishal151 @E-F-J i can explain my nonsense in Paddington land.
=> Application check

app/controllers/projects_controller.rb, app/views/projects/show.html.erb
-Added related projects on project#show
-Limited to 3 but we can change if we feel like it
-Related projects will show only if count > 0
=> Related projects

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_navbar.scss, app/controllers/projects_controller.rb, app/models/project.rb, app/views/components/_difficulty_filter.html.erb, app/views/components/_project_loop.html.erb, app/views/components/_project_search.html.erb, app/views/projects/index.html.erb
@E-F-J @Vishal151 
Projects#index: 
-added search that looks in project title and description. Had to comment out fixed navbar for search to show [sweating intensifies]
-added filters for difficulty levels and date added (most recent, oldest first). Also added 'date uploaded' to project description so that the filter makes more sense.
Also discovered a bug. When creating a new project with multiple technologies they don't show in the project#show. I updated the strong_params and tried to make them accept an array but it's not working. I'll be around tomor...erm today actually to discuss. But now bed.
=> Search projects

.gitignore, Gemfile, Gemfile.lock, app/assets/stylesheets/pages/_home.scss, app/controllers/application_controller.rb, app/models/user.rb, app/views/components/_difficulty_filter.html.erb, app/views/components/_project_loop.html.erb, app/views/devise/registrations/new.html.erb, app/views/users/show.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20200901193749_create_active_storage_tables.active_storage.rb, db/schema.rb
Hi both, I added the photo to users (devise) - it's not rendering on the view for some reason, but I checked it's uploading to cloudinary. We need to decide where/when in the user journey they upload additional profile information too (skills, details, photo)
Did a few other minor edits, like remove the bold from the new project details form etc, but that still has the bug for creating.
Adding PR, in case you want to pick up anything in morning, to limit conflicts..
=> Adding user pictures

app/assets/stylesheets/components/_create-project-form.scss, app/controllers/projects_controller.rb, app/javascript/packs/application.js, app/javascript/packs/highlight_technologies.js, app/views/components/_form_project.html.erb
-Finished styling the form
-Project technologies are clickable tags
=> Create project form

app/views/components/_project_loop.html.erb, app/views/shared/_navbar.html.erb, app/views/users/index.html.erb
Hey both, tiny changes - PR so we have latest version.
I tried looking at user profiles, but we need to decide when/where user input more information after sign-in (descriptions, user technologies etc.), otherwise we get nil-class errors when trying displaying all (it's fine for seeded data as all information is there), or could add some logic not to show users with certain information missing...
=> Sign-up link to right page, small styling edits on user show

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_create-project-form.scss, app/assets/stylesheets/components/_login-form.scss, app/views/components/_form_project.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
-Styled login and sign up forms
-Removed unnecessary code from yday
=> Styling forms

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_project-show.scss, app/controllers/projects_controller.rb, app/views/projects/edit.html.erb, app/views/projects/show.html.erb
Bit of styling for project#edit and project#show pages
-Hiding/showing elements (apply, edit, led by) based on user id for project#show
-Adding form and a container to project#edit
=> Style project show

app/assets/stylesheets/components/_cards_projects_homepage.scss, app/javascript/packs/application.js, app/views/components/_homepage_find_buddies.html.erb, app/views/components/_homepage_latest_projects.html.erb, app/views/layouts/application.html.erb, package-lock.json, package.json, yarn.lock
the carousel needs styling (as do some other bits in the landing page) but here it is for now
=> Trying tiny slider

app/assets/stylesheets/pages/_find_buddies.scss, app/views/users/index.html.erb
Hello @E-F-J , I updated the user index cards (just need to figure out the image scaling (I want all the same size boxes  - plus I remember there's a setting to automatically zoom in on the face), but it looks much better than before - remember to run db:seed to get the pictures for all the users! 
I'll break for a bit, and look at the user edit later
=> User card basic layout, to add photo scaling

app/channels/chatroom_channel.rb, app/controllers/chatrooms_controller.rb, app/controllers/messages_controller.rb, app/javascript/channels/chatroom_channel.js, app/javascript/packs/application.js, app/views/chatrooms/create.html.erb, app/views/chatrooms/destroy.html.erb, app/views/chatrooms/edit.html.erb, app/views/chatrooms/index.html.erb, app/views/chatrooms/new.html.erb, app/views/chatrooms/show.html.erb, app/views/chatrooms/update.html.erb, app/views/messages/_message.html.erb, config/routes.rb, db:check_protected_environments, test/channels/chatroom_channel_test.rb
hey guys, @kkoutoup @Vishal151 action cable implemented
=> Implementing action cable

app/models/project.rb, app/views/components/_form_project.html.erb
@kkoutoup and the coding buddies team @Vishal151 @E-F-J !
I took a peak at the checkbox form and suggest the following fix:
we can place a **checked** attribute on the checkbox input and the **active** class on the checkbox label so that we have a visual representation of the checkboxes that would currently be submitted to the form!
I also made a quick class method **has_technology?(technology)** that returns true/false depending on the presence of that technology (for a given project!)
a little gif here:
http://g.recordit.co/WJ0PyKhkPg.gif
Let me know what you think!
=> fixed project checkboxes :+1

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/config/_body.scss, app/assets/stylesheets/pages/_project-show.scss, app/views/components/_profile_personal_card.html.erb, app/views/components/_project_loop.html.erb, app/views/users/show.html.erb
-Fixing footer
-Fixing related project card styling
-Adding hover zoom effect to related project cards
-Fixing user#show styling
=> Styling pages

app/assets/stylesheets/projects/_project-show.scss, app/views/components/_form_user.html.erb, app/views/users/edit.html.erb
-Very minor stylistic bits
and i'm done for the day
=> Styling bits

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/projects/_project-show.scss, app/assets/stylesheets/reviews/_star-rating.scss, app/helpers/review_helper.rb, app/javascript/packs/application.js, app/javascript/plugins/init_star_rating.js, app/views/components/_render_reviews.html.erb, app/views/reviews/new.html.erb, package.json, yarn.lock
- on review#new
- on project#show
@E-F-J @Vishal151 I think i'll take a break now
=> Implement star rating

app/assets/stylesheets/components/_cards_homepage.scss, app/assets/stylesheets/components/_message.scss, app/controllers/pages_controller.rb, app/javascript/scroll.js, app/views/chatrooms/show.html.erb, app/views/components/_homepage_find_buddies.html.erb, app/views/components/_homepage_latest_projects.html.erb, app/views/messages/_message.html.erb, app/views/users/show.html.erb
Added some more styling to homepage and the chat - still not sure the styling is working fully (I tried to add the JS to render move to right place after message, and also show logged in, own user messages on the right).
=> Front end chat

app/controllers/users_controller.rb, app/javascript/packs/application.js, app/views/components/_modal_edit_user.html.erb, app/views/components/_profile_personal_card.html.erb
this still doesn't update but I thought I'll create the PR and we can look at it together this eve
=> Make pen icon real links

app/controllers/projects_controller.rb, app/views/projects/show.html.erb
here you go @kkoutoup.  Time to go for a walk and ice cream tho, let's look at this tonight :)
=> first implementation logic to display different views in project page

app/assets/stylesheets/projects/_project-show.scss, app/controllers/projects_controller.rb, app/views/components/_show_controls.html.erb, app/views/components/_show_related_projects.html.erb, app/views/components/_show_reviews.html.erb, app/views/projects/show.html.erb, config/routes.rb
=> Implement project completed

app/controllers/projects_controller.rb, app/views/components/_modal_edit_user.html.erb, app/views/projects/show.html.erb
=> modal completed and logic for applying to projects

Gemfile, Gemfile.lock, app/controllers/applications_controller.rb, app/views/components/_homepage_find_buddies.html.erb, app/views/components/_modal_edit_user.html.erb
getting the app ready for heroku
=> set up action cable + logic missing photo

app/controllers/projects_controller.rb, app/views/components/_show_controls.html.erb, app/views/components/_show_related_projects.html.erb, app/views/projects/show.html.erb
the logic to allow for non signed in users to see project index and project show
=> fixed bug for non logged in users

app/assets/stylesheets/users/_profile.scss, app/views/components/_accept_reject_candidates.html.erb, app/views/components/_profile_personal_card.html.erb
styled dashboard to align with similar projects design . need to get the modal back to working status
=> styled dashboard

app/javascript/packs/application.js, app/views/components/_form_user.html.erb, app/views/components/_modal_edit_user.html.erb, app/views/components/_profile_personal_card.html.erb, app/views/messages/_message.html.erb, app/views/users/show.html.erb
=> Testing modal

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/projects/_project-status.scss, app/views/components/_show_project_status.html.erb, app/views/components/_show_related_projects.html.erb, app/views/components/_show_reviews.html.erb, app/views/projects/show.html.erb
Bit of logic of showing elements on project#show when user is signed out.
We should probably test this before accepting branch.
=> Please don't merge: Implement logic show hide content

app/views/messages/_message.html.erb, app/views/projects/show.html.erb
=> List project buddies

app/controllers/messages_controller.rb, app/views/messages/_message.html.erb
=> Brought partial back. Chat is working when profile pic is there

app/helpers/user_helper.rb, app/views/messages/_message.html.erb
=> Yet another improvement on user profile pics. Added helper.

app/helpers/user_helper.rb, config/environments/production.rb
=> completed name cheap config

app/helpers/meta_tags_helper.rb, app/views/layouts/application.html.erb, config/meta.yml
=> checklist to go live

app/assets/stylesheets/pages/_find_buddies.scss, app/assets/stylesheets/users/_users-show.scss, app/helpers/user_helper.rb, app/views/components/_form_user.html.erb, app/views/components/_user_technology_icon.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb
some styling on the user pages
=> style user index and user show

app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/projects/_project-index.scss, app/models/user.rb, app/views/components/_project_loop.html.erb, app/views/components/_project_search.html.erb, app/views/projects/index.html.erb, db/seeds.rb
-Project#index: formatted page and updated cards
-Search form doesn't jump up on click
=> Frontend work

app/assets/stylesheets/pages/_home.scss
=> Aligns how it works on landing page

app/assets/stylesheets/projects/_project-index.scss, app/assets/stylesheets/projects/_project-show.scss, app/views/components/_form_project.html.erb, app/views/components/_project_loop.html.erb, app/views/components/_show_related_projects.html.erb, app/views/layouts/application.html.erb, app/views/projects/index.html.erb, config/meta.yml
-Removed duplicate meta data
-Styled related project cards. Page needs more styling.
=> Style related projects

app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/users/_profile.scss, app/views/components/_profile_personal_card.html.erb
Hi, adding a PR before I head out - updated the dashboard page a bit
@kkoutoup I like your font styling on the project show, so want to update the page with something similar later.
Can message you when I'm back and see where we are.
=> Dashboard design

app/assets/stylesheets/components/_cards_homepage.scss, app/assets/stylesheets/components/_create_project_form.scss, app/assets/stylesheets/projects/_project-show.scss, app/views/components/_form_project.html.erb, app/views/projects/show.html.erb
Changes discussed during our last call.
=> Small tweaks for project index

app/assets/stylesheets/users/_profile.scss, app/views/chatrooms/show.html.erb, app/views/components/_profile_personal_card.html.erb, app/views/shared/_navbar.html.erb
@kkoutoup I corrected the text when technologies are missing on the dashboard.
Also some smalle changes to the chat - this needs more work, but I noticed when I changed some things the messages don't render immediately, so I undid most of the changes for now and checked it's ok! Have a look if you want, or I was planning to raise a ticket later anyway.
=> Dashboard text style

config/cable.yml
=> all change to redis settings

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_message.scss, app/views/chatrooms/show.html.erb, app/views/messages/_message.html.erb, config/application.rb
Hi, I added some more styling to the chatroom and the current user appears on the right of the chat now
Seems to be working when I chat with myself and login as another user
=> Chatroom - current user on right

app/assets/stylesheets/components/_banner_home.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/projects/_project-show.scss, app/views/components/_show_controls.html.erb, app/views/projects/index.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
=> Styling items

app/assets/stylesheets/users/_profile.scss, app/views/users/show.html.erb
-Revamped the user card. Not perfect but we can discuss.
=> New suggested design for user card

app/assets/stylesheets/users/_profile.scss, app/views/components/_homepage_find_buddies.html.erb, app/views/components/_homepage_latest_projects.html.erb, app/views/components/_profile_personal_card.html.erb
a restyling of dashboard (kept in line with the "one card for all user infos" policy) and added capitalize un a few more pages as names in lowercase are ugly :D
=> Tidying up dashboard

app/assets/stylesheets/users/_profile.scss, app/views/users/show.html.erb
-Minor tweaks for user card (i promise)
=> Small style tweaks for user card

app/assets/stylesheets/components/_cards_homepage.scss, app/assets/stylesheets/components/_message.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/users/_profile.scss, app/views/components/_homepage_find_buddies.html.erb, app/views/components/_profile_personal_card.html.erb, app/views/devise/registrations/new.html.erb, app/views/projects/show.html.erb, app/views/users/show.html.erb, db/seeds.rb
Stylistic changes. Not just for chat but site-wide
=> Styling chat

app/assets/stylesheets/components/_cards_homepage.scss, app/views/components/_profile_personal_card.html.erb
Hi @kkoutoup @E-F-J 
A few small fixes:
- Profile page logic/bug-fix for when the level and .capitalize
- Homepage, the project show font size was changing so I fixed so it looks cleaner
We can ticket the chat part on the table - i've not seen the full issue, when chatting with others, as only live chatted with myself :)
=> Styling edits and fixes

app/assets/stylesheets/reviews/_star-rating.scss, app/assets/stylesheets/users/_users-show.scss, app/views/components/_show_related_projects.html.erb, app/views/users/index.html.erb, db/seeds.rb
Seed and styling for buddies page
=> Seed and styling

app/views/components/_profile_personal_card.html.erb, app/views/users/show.html.erb
=> fixed links

app/views/chatrooms/show.html.erb, app/views/components/_profile_personal_card.html.erb, app/views/messages/_message.html.erb
=> Changed image_tag

app/views/messages/_message.html.erb
-Changed image tag in _message.html.erb
=> Possible solution for image chat?
